#!/bin/bash -ex
 
vmname="ubu"
 
ostype="Ubuntu"

isofile="ubuntuserver.iso"
 
memory="2048"

vram="32"
  
hddsize="10240"

vrdeport="5041-5049"
 
#audio="alsa --audiocontroller ac97"

audio="none"

hddfile=/data/virtual_machines/vbox/vbox_guests/${vmname}/${vmname}.vdi
clear

vboxmanage createvm --name $vmname --ostype $ostype --register
vboxmanage modifyvm $vmname --memory $memory --vram $vram --acpi on --ioapic on --cpus 1 --cpuexecutioncap 75 --rtcuseutc on --cpuhotplug on --pae on --hwvirtex on
vboxmanage modifyvm $vmname --nic1 bridged --bridgeadapter1 eth0 --cableconnected1 on
vboxmanage modifyvm $vmname --audio $audio
vboxmanage modifyvm $vmname --vrde on --vrdeport $vrdeport --vrdeauthtype null
vboxmanage storagectl $vmname --name "IDE controller" --add ide
vboxmanage storageattach $vmname --storagectl "IDE controller"  --port 0 --device 0 --type dvddrive --medium $isofile
vboxmanage createhd --filename $hddfile --size $hddsize
vboxmanage storagectl $vmname --name "SATA controller" --add sata
vboxmanage storageattach $vmname --storagectl "SATA controller" --port 0 --device 0 --type hdd --medium $hddfile
